import createClient, { type Client, type Middleware } from "openapi-fetch"
import type { paths } from "../../generated/openapispec.ts" // generated by openapi-typescript
import { apiLogger, type LoggingOptions } from "../logger/logging.ts"
import { loggerMiddleware } from "../logger/middleware.ts"


/**
 * interface for passing options to the sdk
 */
export interface iOptions {
   /** client-id for the API */
   client_id?: string
   /** client-secret for the API */
   client_secret?: string
   /** base url for the content management API */
   base_url?: string
   /** enables debugging to show calls to the API endpoint, disabled by default */
   debug?: boolean
   /**
    * Wire SDK logs to a file and/or the console. When set, `cmssdk` calls
    * {@link configureLogging} for you. For guaranteed capture of the first
    * request, prefer calling `await configureLogging(...)` yourself before
    * creating the client.
    */
   logging?: LoggingOptions
}

const createTypedSdk = (options: iOptions): Client<paths> => {
   const APIVERSION = "v1"
   const clientid = options.client_id
   const clientsecret = options.client_secret
   const baseurl = options.base_url

      // Functional state held in the closure
   let cachedToken: string | null = null
   let tokenExpiresAt: number = 0 // Timestamp in milliseconds

   const auth = async (): Promise<{ access_token: string; expires_in: number }> => {
      try {
         const response = await fetch(`${baseurl}/oauth/token`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
               grant_type: "client_credentials",
               client_id: clientid,
               client_secret: clientsecret,
            }),
         })

         if (!response.ok) throw new Error(`Failed to authenticate: ${response.status} ${response.statusText}`)

         return response.json()
      }
      catch (_error) {
         throw new Error("No network connection") // this should only show when network is not available
      }
   }

   const getToken = async (): Promise<string> => {
      const now = Date.now()

      // Check if token exists and is still valid (with a 10-second buffer for safety)
      if (cachedToken && now < tokenExpiresAt - 10000) {
         apiLogger.debug(`Using cached token.`)
         return cachedToken
      }
      apiLogger.debug(`Requesting new OAuth token...`)
      // Otherwise, fetch a new one and update the closure state
      const data = await auth()
      cachedToken = data.access_token
      // expires_in is usually in seconds, convert to milliseconds timestamp
      tokenExpiresAt = Date.now() + data.expires_in * 1000

      return cachedToken
   }

   const authMiddleware: Middleware = {
      async onRequest({ request }) {
         const token = await getToken()
         // add Authorization header to every request
         request.headers.set("Authorization", `Bearer ${token}`)
         return request
      }
   }

   const client = createClient<paths>({ baseUrl: `${baseurl}/${APIVERSION}` })
   client.use(authMiddleware)
   // Always attach: the middleware only emits to the api-level logger, which is
   // a no-op until a sink is configured (see configureLogging). `debug` is kept
   // for backwards compatibility and handled by the caller (sdk.ts).
   client.use(loggerMiddleware)
   return client
}

// Shared default client. Building it once keeps the OAuth token cache (held in
// createTypedSdk's closure) alive across calls, instead of re-authenticating on
// every request as a fresh per-call client would.
let cachedClient: ReturnType<typeof createTypedSdk> | null = null

export const typedsdk = (options: iOptions, shared = false): Client<paths> => {
   // Explicit credentials get a dedicated client (callers control their own credentials).
   if (!shared) return createTypedSdk(options)
   // Otherwise reuse the shared client so the token is cached between requests.
   if (!cachedClient) cachedClient = createTypedSdk(options)
   return cachedClient
}

// The openapi-fetch client instance shared by the resource modules.
export type TypedSdkClient = Client<paths>
