import createClient, { type Client, type Middleware } from "openapi-fetch"
import type { paths } from "../../generated/openapispec.ts" // generated by openapi-typescript

export interface iOptions {
   client_id?: string
   client_secret?: string
   base_url?: string
   debug?: boolean
}

const createTypedSdk = (options: iOptions): Client<paths> => {
   const APIVERSION = "v1"
   const clientid = options.client_id
   const clientsecret = options.client_secret
   const baseurl = options.base_url
   const debug = options.debug

      // Functional state held in the closure
   let cachedToken: string | null = null
   let tokenExpiresAt: number = 0 // Timestamp in milliseconds

   const auth = async (): Promise<{ access_token: string; expires_in: number }> => {
      const response = await fetch(`${baseurl}/oauth/token`, {
         method: "POST",
         headers: { "Content-Type": "application/json" },
         body: JSON.stringify({
            grant_type: "client_credentials",
            client_id: clientid,
            client_secret: clientsecret,
         }),
      })

      if (!response.ok) throw new Error(`Failed to authenticate: ${response.status} ${response.statusText}`)

      return response.json()
   }

   const getToken = async (): Promise<string> => {
      const now = Date.now()

      // Check if token exists and is still valid (with a 10-second buffer for safety)
      if (cachedToken && now < tokenExpiresAt - 10000) {
         if (debug) console.log(`[OptiCMS] Using cached token.`)
         return cachedToken
      }
      if (debug) console.log(`[OptiCMS] Requesting new OAuth token...`)
      // Otherwise, fetch a new one and update the closure state
      const data = await auth()
      cachedToken = data.access_token
      // expires_in is usually in seconds, convert to milliseconds timestamp
      tokenExpiresAt = Date.now() + data.expires_in * 1000

      return cachedToken
   }

   const authMiddleware: Middleware = {
      async onRequest({ request }) {
         const token = await getToken()
         // add Authorization header to every request
         request.headers.set("Authorization", `Bearer ${token}`)
         return request
      },
   }

   const client = createClient<paths>({ baseUrl: `${baseurl}/${APIVERSION}` })
   client.use(authMiddleware)
   return client
}

// Shared default client. Building it once keeps the OAuth token cache (held in
// createTypedSdk's closure) alive across calls, instead of re-authenticating on
// every request as a fresh per-call client would.
let cachedClient: ReturnType<typeof createTypedSdk> | null = null

export const typedsdk = (options: iOptions, shared = false): Client<paths> => {
   // Explicit credentials get a dedicated client (callers control their own credentials).
   if (!shared) return createTypedSdk(options)
   // Otherwise reuse the shared client so the token is cached between requests.
   if (!cachedClient) cachedClient = createTypedSdk(options)
   return cachedClient
}

// The openapi-fetch client instance shared by the resource modules.
export type TypedSdkClient = Client<paths>
